services:
  motorcycle-rental-api:
    container_name: motorcycle-rental-api
    build:
      dockerfile: MotorcycleRental.API/Dockerfile
      context: .
    ports:
      - 32777:8080
      - 32778:8081
    networks:
      motorcycle-networks:
    depends_on: ["postgres-docker","rabbit-docker"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  postgres-docker:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MotorcycleRental@123
      POSTGRES_DB: MotorcycleRental
    ports:
      - "5433:5432"
    networks:
      motorcycle-networks:
        aliases:
          - pghost
          
  rabbit-docker:
    image: rabbitmq:3-management
    container_name: rabbit-docker
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      motorcycle-networks:

networks:
  motorcycle-networks:
    driver: bridge