services:
  motorcycle-rental-api:
    container_name: motorcycle-rental-api
    build:
      dockerfile: MotorcycleRental.API/Dockerfile
      context: .
    ports:
      - 3000:80
      - 3001:443
    networks:
      motorcycle-networks:
    depends_on: ["postgres-docker", "rabbitdocker"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - RABBITMQ_URL=rabbitdocker
      - POSTGRES_URL=postgres-docker

  postgres-docker:
    image: postgres:latest
    restart: always
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MotorcycleRental@123
      POSTGRES_DB: MotorcycleRental
    ports:
      - "5433:5432"
    networks:
      motorcycle-networks:
          
  rabbitdocker:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitdocker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      motorcycle-networks:

networks:
  motorcycle-networks:
    driver: bridge